name: Build Android SDK Tools

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: r26b
      ABI: arm64-v8a

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3 python3-pip cmake ninja-build \
          build-essential unzip curl git openjdk-11-jdk

    - name: Download Android NDK
      run: |
        curl -O https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip
        unzip android-ndk-${NDK_VERSION}-linux.zip
        mv android-ndk-${NDK_VERSION} android-ndk

    - name: Fetch AOSP sources
      run: |
        python3 get_source.py --tags platform-tools-35.0.2

    - name: Build protobuf (host)
      run: |
        cd src/protobuf
        mkdir build && cd build
        cmake -GNinja \
          -Dprotobuf_BUILD_TESTS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          ../cmake
        ninja -j$(nproc)

    - name: Build SDK tools
      run: |
        PROTOC=$(realpath src/protobuf/build/protoc)
        python3 build.py \
          --ndk=$(realpath android-ndk) \
          --abi=${ABI} \
          --build=build/${ABI} \
          --protoc=${PROTOC}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sdk-tools-${{ env.ABI }}
        path: build/${{ env.ABI }}
